# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/grid_pixel',
                'doc_host': 'https://Ahmed-Khaled-Saleh.github.io',
                'git_url': 'https://github.com/Ahmed-Khaled-Saleh/grid_pixel',
                'lib_path': 'grid_pixel'},
  'syms': {'grid_pixel.core': {'grid_pixel.core.foo': ('core.html#foo', 'grid_pixel/core.py')}}}
